googleAnalytics = "G-YXFJCKLYLT"
baseURL = 'https://ankilp.github.io'
languageCode = 'en-us'
title = 'Ankil Patel'
theme = "papermod"

paginate=15
enableInlineShortcodes = true
enableRobotsTXT = true

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

[params]
env = "production"
author = "Ankil"
defaultTheme = "dark"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false
Comments = true

  [params.homeInfoParams]
  Title = "Welcome to my personal blog!"
  Content = """
Please note that all opinions are my own. I'm currently a software engineer at Salesforce. Feel free to chat with me regarding any of my previous work at Salesforce, Electronic Arts, Thales or the University of Waterloo. 

I've also had brushes with research and startups:
* Plasma attenuation for electrodeposition at Chalk River Labs
* Image Processing with Shapelet functions
* Protein modelling for prion aggregation
* Fluid modelling for nanocellulose (Unnamed startup)
* Fluid modelling for cryocoolers (Intelline)
* Privacy preserving ML (EnSnif)
* Explicit vs implicit associations in curriculum learning for reinforcement learning

I love travelling and reading. I've found a way to combine the two by picking up a book written by a local author in every new city I visit. 
"""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/AnkilP"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/ankil-patel"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:ankil335@gmail.com"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/randommoleculez"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true
